server:
  port: 8090
  context-path: /techno
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techno?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxIdle: 30
    maxWait: 60000  #获取连接等待超时时间
    timeBetweenEvictionRunsMillis: 60000  #关闭空闲连接间隔检测时间
    minEvictableIdleTimeMillis: 300000  #单个连接在池中最小存活时间
    filters: stat,wall,slf4j  #配置监控拦截的filters,去掉后无法统计sql，wall用于防火墙
    useGlobalDataSourceStat: true #合并多个监控数据
    loginUsername: druid
    loginPassword:  druid
    allow:  #ip白名单，为空时所有都可访问
#    deny: #ip黑名单，若与白名单冲突，优先级高于白名单
    restEnable: false #禁用HTML页面的 Rest all 功能
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    cache: false   #不启用缓存

#  redis:
#    database: 0
#    host: 127.0.0.1
#    password:
#    port: 6379
#    timeout: 1000
#    pool:
#      max-idle: 8 #最大空闲连接数，默认为8
#      min-idle: 0 #最小空闲连接数，默认为0
#      max-wait: 1000 #等待可用连接最大时间，默认为-1，表示永不超时（超时抛出JedisConnectionException）
#      max-active: 500 #分配Jedis实例，若达到该数量，则pool耗尽；-1表示无限制

management:
  context-path: /manage
  security:
    enabled: true
    roles: ADMIN
    sessions: stateless

logging:
  level:
    com.jason.techno.control: debug
